# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relations',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
